
import {expect} from '@jest/globals';

import {default as cryptian} from '../..';

const {algorithm, mode} = cryptian;

// Known answer vectors for Twofish, taken from the published test data
// rather than generated by this implementation, so they check the cipher
// against the specification and not against itself.
describe('twofish known answer vectors', () => {

    it('reports the block and key sizes from the specification', () => {

        const twofish = new algorithm.Twofish();

        expect(twofish.getBlockSize()).toBe(16);
        expect(twofish.getKeySizes()).toEqual([16, 24, 32]);
        expect(twofish.getName()).toBe('twofish');
    });

    describe('128 bit key', () => {

        const vectors = [
            {key: '9F589F5CF6122C32B6BFEC2F2AE8C35A', plaintext: 'D491DB16E7B1C39E86CB086B789F5419', ciphertext: '019F9809DE1711858FAAC3A3BA20FBC3'},
            {key: 'D491DB16E7B1C39E86CB086B789F5419', plaintext: '019F9809DE1711858FAAC3A3BA20FBC3', ciphertext: '6363977DE839486297E661C6C9D668EB'},
            {key: '019F9809DE1711858FAAC3A3BA20FBC3', plaintext: '6363977DE839486297E661C6C9D668EB', ciphertext: '816D5BD0FAE35342BF2A7412C246F752'},
            {key: '6363977DE839486297E661C6C9D668EB', plaintext: '816D5BD0FAE35342BF2A7412C246F752', ciphertext: '5449ECA008FF5921155F598AF4CED4D0'},
            {key: '816D5BD0FAE35342BF2A7412C246F752', plaintext: '5449ECA008FF5921155F598AF4CED4D0', ciphertext: '6600522E97AEB3094ED5F92AFCBCDD10'},
            {key: '5449ECA008FF5921155F598AF4CED4D0', plaintext: '6600522E97AEB3094ED5F92AFCBCDD10', ciphertext: '34C8A5FB2D3D08A170D120AC6D26DBFA'},
            {key: '6600522E97AEB3094ED5F92AFCBCDD10', plaintext: '34C8A5FB2D3D08A170D120AC6D26DBFA', ciphertext: '28530B358C1B42EF277DE6D4407FC591'},
            {key: '34C8A5FB2D3D08A170D120AC6D26DBFA', plaintext: '28530B358C1B42EF277DE6D4407FC591', ciphertext: '8A8AB983310ED78C8C0ECDE030B8DCA4'},
            {key: '28530B358C1B42EF277DE6D4407FC591', plaintext: '8A8AB983310ED78C8C0ECDE030B8DCA4', ciphertext: '48C758A6DFC1DD8B259FA165E1CE2B3C'},
            {key: '8A8AB983310ED78C8C0ECDE030B8DCA4', plaintext: '48C758A6DFC1DD8B259FA165E1CE2B3C', ciphertext: 'CE73C65C101680BBC251C5C16ABCF214'},
            {key: '48C758A6DFC1DD8B259FA165E1CE2B3C', plaintext: 'CE73C65C101680BBC251C5C16ABCF214', ciphertext: 'C7ABD74AA060F78B244E24C71342BA89'},
            {key: 'CE73C65C101680BBC251C5C16ABCF214', plaintext: 'C7ABD74AA060F78B244E24C71342BA89', ciphertext: 'D0F8B3B6409EBCB666D29C916565ABFC'},
        ];

        vectors.forEach(({key, plaintext, ciphertext}, index) => {

            it('encrypts vector ' + index, () => {

                const twofish = new algorithm.Twofish();
                twofish.setKey(Buffer.from(key, 'hex'));

                expect(twofish.encrypt(Buffer.from(plaintext, 'hex')).toString('hex'))
                    .toBe(ciphertext.toLowerCase());
            });

            it('decrypts vector ' + index, () => {

                const twofish = new algorithm.Twofish();
                twofish.setKey(Buffer.from(key, 'hex'));

                expect(twofish.decrypt(Buffer.from(ciphertext, 'hex')).toString('hex'))
                    .toBe(plaintext.toLowerCase());
            });
        });
    });

    describe('192 bit key', () => {

        const vectors = [
            {key: 'EFA71F788965BD4453F860178FC191010000000000000000', plaintext: '88B2B2706B105E36B446BB6D731A1E88', ciphertext: '39DA69D6BA4997D585B6DC073CA341B2'},
            {key: '88B2B2706B105E36B446BB6D731A1E88EFA71F788965BD44', plaintext: '39DA69D6BA4997D585B6DC073CA341B2', ciphertext: '182B02D81497EA45F9DAACDC29193A65'},
            {key: '39DA69D6BA4997D585B6DC073CA341B288B2B2706B105E36', plaintext: '182B02D81497EA45F9DAACDC29193A65', ciphertext: '7AFF7A70CA2FF28AC31DD8AE5DAAAB63'},
            {key: '182B02D81497EA45F9DAACDC29193A6539DA69D6BA4997D5', plaintext: '7AFF7A70CA2FF28AC31DD8AE5DAAAB63', ciphertext: 'D1079B789F666649B6BD7D1629F1F77E'},
            {key: '7AFF7A70CA2FF28AC31DD8AE5DAAAB63182B02D81497EA45', plaintext: 'D1079B789F666649B6BD7D1629F1F77E', ciphertext: '3AF6F7CE5BD35EF18BEC6FA787AB506B'},
            {key: 'D1079B789F666649B6BD7D1629F1F77E7AFF7A70CA2FF28A', plaintext: '3AF6F7CE5BD35EF18BEC6FA787AB506B', ciphertext: 'AE8109BFDA85C1F2C5038B34ED691BFF'},
            {key: '3AF6F7CE5BD35EF18BEC6FA787AB506BD1079B789F666649', plaintext: 'AE8109BFDA85C1F2C5038B34ED691BFF', ciphertext: '893FD67B98C550073571BD631263FC78'},
            {key: 'AE8109BFDA85C1F2C5038B34ED691BFF3AF6F7CE5BD35EF1', plaintext: '893FD67B98C550073571BD631263FC78', ciphertext: '16434FC9C8841A63D58700B5578E8F67'},
            {key: '893FD67B98C550073571BD631263FC78AE8109BFDA85C1F2', plaintext: '16434FC9C8841A63D58700B5578E8F67', ciphertext: '9594CF62D48ACD347A68A3161F0F3EE7'},
            {key: '16434FC9C8841A63D58700B5578E8F67893FD67B98C55007', plaintext: '9594CF62D48ACD347A68A3161F0F3EE7', ciphertext: 'B23E8C2C731C514017D1F2B88D77D208'},
            {key: '9594CF62D48ACD347A68A3161F0F3EE716434FC9C8841A63', plaintext: 'B23E8C2C731C514017D1F2B88D77D208', ciphertext: '93CC592BC96D95FA8AC32DA894F6AB89'},
            {key: 'B23E8C2C731C514017D1F2B88D77D2089594CF62D48ACD34', plaintext: '93CC592BC96D95FA8AC32DA894F6AB89', ciphertext: '26516E6BD4AEF86AF4F4AD58FA41A14C'},
        ];

        vectors.forEach(({key, plaintext, ciphertext}, index) => {

            it('encrypts vector ' + index, () => {

                const twofish = new algorithm.Twofish();
                twofish.setKey(Buffer.from(key, 'hex'));

                expect(twofish.encrypt(Buffer.from(plaintext, 'hex')).toString('hex'))
                    .toBe(ciphertext.toLowerCase());
            });

            it('decrypts vector ' + index, () => {

                const twofish = new algorithm.Twofish();
                twofish.setKey(Buffer.from(key, 'hex'));

                expect(twofish.decrypt(Buffer.from(ciphertext, 'hex')).toString('hex'))
                    .toBe(plaintext.toLowerCase());
            });
        });
    });

    describe('256 bit key', () => {

        const vectors = [
            {key: '57FF739D4DC92C1BD7FC01700CC8216F00000000000000000000000000000000', plaintext: 'D43BB7556EA32E46F2A282B7D45B4E0D', ciphertext: '90AFE91BB288544F2C32DC239B2635E6'},
            {key: 'D43BB7556EA32E46F2A282B7D45B4E0D57FF739D4DC92C1BD7FC01700CC8216F', plaintext: '90AFE91BB288544F2C32DC239B2635E6', ciphertext: '6CB4561C40BF0A9705931CB6D408E7FA'},
            {key: '90AFE91BB288544F2C32DC239B2635E6D43BB7556EA32E46F2A282B7D45B4E0D', plaintext: '6CB4561C40BF0A9705931CB6D408E7FA', ciphertext: '3059D6D61753B958D92F4781C8640E58'},
            {key: '6CB4561C40BF0A9705931CB6D408E7FA90AFE91BB288544F2C32DC239B2635E6', plaintext: '3059D6D61753B958D92F4781C8640E58', ciphertext: 'E69465770505D7F80EF68CA38AB3A3D6'},
            {key: '3059D6D61753B958D92F4781C8640E586CB4561C40BF0A9705931CB6D408E7FA', plaintext: 'E69465770505D7F80EF68CA38AB3A3D6', ciphertext: '5AB67A5F8539A4A5FD9F0373BA463466'},
            {key: 'E69465770505D7F80EF68CA38AB3A3D63059D6D61753B958D92F4781C8640E58', plaintext: '5AB67A5F8539A4A5FD9F0373BA463466', ciphertext: 'DC096BCD99FC72F79936D4C748E75AF7'},
            {key: '5AB67A5F8539A4A5FD9F0373BA463466E69465770505D7F80EF68CA38AB3A3D6', plaintext: 'DC096BCD99FC72F79936D4C748E75AF7', ciphertext: 'C5A3E7CEE0F1B7260528A68FB4EA05F2'},
            {key: 'DC096BCD99FC72F79936D4C748E75AF75AB67A5F8539A4A5FD9F0373BA463466', plaintext: 'C5A3E7CEE0F1B7260528A68FB4EA05F2', ciphertext: '43D5CEC327B24AB90AD34A79D0469151'},
            {key: 'C5A3E7CEE0F1B7260528A68FB4EA05F2DC096BCD99FC72F79936D4C748E75AF7', plaintext: '43D5CEC327B24AB90AD34A79D0469151', ciphertext: '05BA7BE9BE5274FBEB4AC5FD5FAAFA10'},
            {key: '43D5CEC327B24AB90AD34A79D0469151C5A3E7CEE0F1B7260528A68FB4EA05F2', plaintext: '05BA7BE9BE5274FBEB4AC5FD5FAAFA10', ciphertext: '89D513B989E3CECE4D2E3E4C15D4E01C'},
            {key: '05BA7BE9BE5274FBEB4AC5FD5FAAFA1043D5CEC327B24AB90AD34A79D0469151', plaintext: '89D513B989E3CECE4D2E3E4C15D4E01C', ciphertext: 'E56E462AE2E66F800CE2224C4CAFACBE'},
            {key: '89D513B989E3CECE4D2E3E4C15D4E01C05BA7BE9BE5274FBEB4AC5FD5FAAFA10', plaintext: 'E56E462AE2E66F800CE2224C4CAFACBE', ciphertext: 'F5DBEE5414D79CA46BE17346FDC72BF5'},
        ];

        vectors.forEach(({key, plaintext, ciphertext}, index) => {

            it('encrypts vector ' + index, () => {

                const twofish = new algorithm.Twofish();
                twofish.setKey(Buffer.from(key, 'hex'));

                expect(twofish.encrypt(Buffer.from(plaintext, 'hex')).toString('hex'))
                    .toBe(ciphertext.toLowerCase());
            });

            it('decrypts vector ' + index, () => {

                const twofish = new algorithm.Twofish();
                twofish.setKey(Buffer.from(key, 'hex'));

                expect(twofish.decrypt(Buffer.from(ciphertext, 'hex')).toString('hex'))
                    .toBe(plaintext.toLowerCase());
            });
        });
    });

    // The raw encrypt and decrypt entry points take exactly one block. Data
    // longer than that goes through a mode, so these multi block vectors are
    // run through ecb, which is what an application would use.
    describe('multiple blocks through ecb', () => {

        const vectors = [
            {key: '00000000000000000000000000000000', plaintext: '000000000000000000000000000000009F589F5CF6122C32B6BFEC2F2AE8C35A', ciphertext: '9F589F5CF6122C32B6BFEC2F2AE8C35AD491DB16E7B1C39E86CB086B789F5419'},
            {key: '000000000000000000000000000000000000000000000000', plaintext: '00000000000000000000000000000000EFA71F788965BD4453F860178FC19101', ciphertext: 'EFA71F788965BD4453F860178FC1910188B2B2706B105E36B446BB6D731A1E88'},
            {key: '0000000000000000000000000000000000000000000000000000000000000000', plaintext: '0000000000000000000000000000000057FF739D4DC92C1BD7FC01700CC8216F', ciphertext: '57FF739D4DC92C1BD7FC01700CC8216FD43BB7556EA32E46F2A282B7D45B4E0D'},
        ];

        vectors.forEach(({key, plaintext, ciphertext}, index) => {

            it('round trips vector ' + index, () => {

                const encryptKey = new algorithm.Twofish();
                encryptKey.setKey(Buffer.from(key, 'hex'));

                const decryptKey = new algorithm.Twofish();
                decryptKey.setKey(Buffer.from(key, 'hex'));

                const cipher = new mode.ecb.Cipher(encryptKey, Buffer.alloc(0));
                const decipher = new mode.ecb.Decipher(decryptKey, Buffer.alloc(0));

                expect(cipher.transform(Buffer.from(plaintext, 'hex')).toString('hex'))
                    .toBe(ciphertext.toLowerCase());
                expect(decipher.transform(Buffer.from(ciphertext, 'hex')).toString('hex'))
                    .toBe(plaintext.toLowerCase());
            });
        });
    });
});
